### ISSUE TITLE
Y-axis of chart should be in `MvB`

### ISSUE THREAD

**Issue by Xekyo** [mempool-space/mempool.space#14]
Hey Simon,

Love your mempool visualization. We have mempool.space/tv up in our office 24/7. :)
A couple colleagues just came around to ask how to read it, and I was wondering why the y-axis is in `MB` and not in `MvB` given that the dotted line should correspond to `1 MvB` or `4 MWU`. Given that the next block will include up to `1 MvB` of data, it would make sense to me to show the queue in weight rather than data size.

**Comment by softsimon** [comment]
The y-axis is in virtual bytes to be able to show the mempool size in "block size".

I believe changing to MvB would make most sense rather than changing to 4 MB MWU.

What do you think?

**Comment by wiz** [comment]
+1 for MvB

**Comment by Xekyo** [comment]
Yeah, that's what I meant: given that the dotted line should be corresponding to the actual blockspace limit, the y-axis should be corresponding to virtual size (MvB) or weight (MWU) instead of raw datasize (MB). So, exactly what I was going for! Thanks for the quick response.
