### ISSUE TITLE
Block explorer URL is hardcoded

### ISSUE THREAD

**Issue by gustavonalle** [mempool-space/mempool.space#19]
The frontend always goes to https://www.blockstream.info, it should be possible to make it configurable so that users can point to their local Esplora instance

**Comment by softsimon** [comment]
With the upcoming explorer interface when esplora is enabled, the blockstream.info linkes will be replaced. https://github.com/mempool-space/mempool.space/tree/esplora

**Comment by gustavonalle** [comment]
I tried with the latest master where I specified ```"ELECTRS_API_URL": "https://myesplora/api"``` and it still links to block stream. What should I change besides that?

**Comment by softsimon** [comment]
I guess you are referring to the blockstream links in the front end? It's hard coded. You need to build / run the front end with a electrs parameter --configuration=electrs     npm run build-electrs  works.

**Comment by softsimon** [comment]
In master, the block explorer url is no longer hard coded as mempool space now is its own block explorer.
