### ISSUE TITLE
Scrollbar hidden on Graphs and About tabs in some conditions

### ISSUE THREAD

**Issue by Amiga500** [mempool-space/mempool.space#26]
Graphs and About tabs have the scrollbar. 
If i enter before on TV view tab and then go on Graphs or About the scrollbar is hide. (Tested on chrome and firefox pressing the button to come back, it works only if i delete "/tv" from the address page of browser).
To see again the scrollbar on these two tabs i have to go into Blocks and enter again there.
(This issue was present on older releases too)

**Comment by rbrooklyn** [comment]
Steps to reproduce:

- Click Graphs button option along the top
- Click TV View
- Press back in browser
- User will now be in "Graphs" section, but cannot vertically scroll, as "disable-scroll" class remains applied to the body tag
- Press About
- User again cannot scroll.

Expected result:
- User able to vertically scroll after navigating back from the TV view feature to the Graphs or About features as "disable-scroll" class should be removed

Workaround for user:
- User can reload, this fixes in all cases
- User can also go to "Blocks" option and then navigate from there, as this also fixes it

Notes
blockchain.component.ts has this code, which I believe removes the disable-scroll class when needed:
```
  ngOnDestroy() {
    this.blocksSubscription.unsubscribe();
    this.txTrackingSubscription.unsubscribe();
    this.renderer.removeClass(document.body, 'disable-scroll');
  }
```
However, adding similar to television.component.ts has no affect:
```
ngOnDestroy() {
    this.renderer.removeClass(document.body, 'disable-scroll');
  }
```

**Comment by softsimon** [comment]
Fixed in master
