### ISSUE TITLE
Letsencrypt How-To

### ISSUE THREAD

**Issue by sako0938** [mempool-space/mempool.space#6]
Very Close to having this working. I am stuck on starting nginx and it failing to find /etc/letsencrypt/options-ssl-nginx.conf

My setup would prefer to use port 80, as I will get the certificate another way. Do you know how I can edit the nginx.conf to allow me to do that?

**Comment by sako0938** [comment]
Ended up with nginx.conf looking like this:
`user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {
	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	gzip on;
	gzip_comp_level    5;
	gzip_min_length    256;
	gzip_proxied       any;
	gzip_vary          on;

	gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy; # text/html is always compressed by gzip module

	server {

		listen 80;
		listen [::]:80;
		#server_name mempool.space;
		root /var/www/html;

		index index.html index.htm index.nginx-debian.html;
		server_name mempool.space; # managed by Certbot

		location / {
			try_files $uri $uri/ /index.html =404;
		}

		location /api {
			proxy_pass http://127.0.0.1:8999/api;
		}

		location /ws {
			proxy_pass http://127.0.0.1:8999/;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "Upgrade";
		}
	}
}`

I've got a beautiful UI going, and it seems the backend is running properly, but a bit slow on my Odroid XU4. Stuck on "loading blocks"

**Comment by wiz** [comment]
Hey @sako0938 I pushed some updates a few hours ago which might fix your getting stuck on "loading blocks" - this means it's unable to connect to websocket for some reason. Please DM me on Keybase @wiz if you want to discuss.

**Comment by wiz** [comment]
As for certbot, this is out of scope but `apt install python-certbot-nginx` and `certbot -d example.com` should get you an SSL certificate

**Comment by wiz** [comment]
@sako0938 I've updated the installation instructions and nginx.conf, please let me know if this works better with certbot / let's encrypt

**Comment by sako0938** [comment]
Hey thanks @wiz ! With these new changes I have a working mempool.space I am still using my nginx.conf from above to serve on port 80, but thanks for adding in those instruction for letsencrypt.

Should the backend be able to run continuously if you close the terminal window, since nginx already can? I was working on this command ```nohup node dist/index.js > /usr/src/app/mempool.space.log 2> /usr/src/app/mempool.space.error.log < /dev/null &```, until I noticed the backend was already running and everything was working!!

**Comment by wiz** [comment]
Yeah we need to properly daemonize the backend, I'll create a new issue for that. Glad you got it working! 👍
